# Generated by Django 5.2.17 on 2026-10-06 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_tutor',
            field=models.ForeignKey(blank=True, help_text='Selected tutor for students during self-registration.', limit_choices_to={'role': 'TUTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospective_students', to=settings.AUTH_USER_MODEL, verbose_name='Selected Tutor'),
        ),
    ]
