# Generated by Django 5.2.17 on 2026-10-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_selected_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Set when someone else chose the password (tutor-created account or tutor reset). The user is asked for a new one at next sign-in.', verbose_name='Must Change Password'),
        ),
    ]
