# Generated by Django 5.2.16 on 2026-10-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_account_and_marking_upgrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tutor_code',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated 6-char invite code for tutors. Students use this to connect.', max_length=8, null=True, unique=True, verbose_name='Tutor Code'),
        ),
    ]
