# Generated by Django 5.2.17 on 2026-10-06 05:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_number', models.PositiveIntegerField(default=1, help_text='Auto-incremented on each reset. Cycle #1 is the first.', verbose_name='Cycle Number')),
                ('fee_snapshot', models.DecimalField(decimal_places=2, default=0.0, help_text='Copy of tuition_fee at the time this cycle was created.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fee Snapshot')),
                ('total_classes', models.PositiveIntegerField(default=12, help_text='Copy of cycle_length at the time this cycle was created.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Classes')),
                ('classes_data', models.JSONField(default=list, help_text='JSON array tracking completion status and date for each class.', verbose_name='Classes Data')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=10, verbose_name='Cycle Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_cycles', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_cycles', to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
                'ordering': ['student', '-cycle_number'],
                'indexes': [models.Index(fields=['tutor', 'status'], name='cycles_cycl_tutor_i_7bf67b_idx'), models.Index(fields=['student', 'status'], name='cycles_cycl_student_06e253_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student',), name='unique_active_cycle_per_student')],
            },
        ),
    ]
