# Generated by Django 5.2.17 on 2026-10-06 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
        ('students', '0003_tuition_tuitionenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_number', models.PositiveIntegerField(default=1, help_text='Auto-incremented on each reset. Cycle #1 is the first.', verbose_name='Cycle Number')),
                ('classes_data', models.JSONField(default=list, help_text='[{"class_no": 1, "completed": True, "date": "2026-10-06", "topic": "..."}]', verbose_name='Classes Attendance Data')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=10, verbose_name='Cycle Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='students.tuitionenrollment', verbose_name='Tuition Enrollment')),
            ],
            options={
                'verbose_name': 'Attendance Cycle',
                'verbose_name_plural': 'Attendance Cycles',
                'ordering': ['enrollment', '-cycle_number'],
            },
        ),
    ]
