# Generated by Django 5.2.17 on 2026-10-06 12:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_attendancecycle'),
        ('students', '0004_tuition_description_tuition_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecycle',
            name='fee_snapshot',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Copy of tuition_fee at the time this cycle was created.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fee Snapshot'),
        ),
        migrations.AddField(
            model_name='attendancecycle',
            name='total_classes',
            field=models.PositiveIntegerField(default=12, help_text='Copy of cycle_length at the time this cycle was created.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Classes'),
        ),
        migrations.AddField(
            model_name='attendancecycle',
            name='tutor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TUTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuition_cycles', to=settings.AUTH_USER_MODEL, verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='attendancecycle',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles', to='students.tuitionenrollment', verbose_name='Tuition Enrollment'),
        ),
        migrations.AddConstraint(
            model_name='attendancecycle',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('enrollment',), name='unique_active_attendance_cycle_per_enrollment'),
        ),
    ]
