# Generated by Django 5.2.17 on 2026-10-06 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0003_attendancecycle_fee_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecycle',
            name='total_classes_snapshot',
            field=models.PositiveIntegerField(default=12, help_text='Frozen copy of cycle_length at cycle creation.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Classes Snapshot'),
        ),
    ]
