# Generated by Django 5.2.17 on 2026-10-06 17:15

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0005_attendancecycle_shared_per_tuition'),
        ('students', '0009_group_tuition_and_connection_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancecycle',
            options={'ordering': ['tuition', '-cycle_number'], 'verbose_name': 'Attendance Cycle', 'verbose_name_plural': 'Attendance Cycles'},
        ),
        migrations.RemoveField(
            model_name='attendancecycle',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='attendancecycle',
            name='total_classes_snapshot',
        ),
        migrations.AlterField(
            model_name='attendancecycle',
            name='classes_data',
            field=models.JSONField(default=list, help_text='[{"class_no": 1, "completed": true, "date": "2026-10-06T10:00:00Z", "topic": "..."}]', verbose_name='Classes Attendance Data'),
        ),
        migrations.AlterField(
            model_name='attendancecycle',
            name='fee_snapshot',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="The tuition's total_fee for this cycle (whole group).", max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Fee Snapshot'),
        ),
        migrations.AlterField(
            model_name='attendancecycle',
            name='total_classes',
            field=models.PositiveIntegerField(default=12, help_text="The tuition's cycle_length for this cycle.", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Classes'),
        ),
        migrations.AddConstraint(
            model_name='attendancecycle',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('tuition',), name='unique_active_attendance_cycle_per_tuition'),
        ),
    ]
