# Generated by Django 5.2.17 on 2026-10-06 05:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Exam Title')),
                ('content_html', models.TextField(help_text='Stores sanitized HTML from the TipTap rich-text editor. Includes formatted text, tables, and KaTeX math delimiters. NEVER stored raw — always sanitized via nh3 before persistence.', verbose_name='Exam Content (Sanitized HTML)')),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Marks')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='Start Time (UTC)')),
                ('end_time', models.DateTimeField(db_index=True, verbose_name='End Time (UTC)')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Informational. If set, displayed to student as exam duration.', null=True, verbose_name='Duration (Minutes)')),
                ('grace_period_minutes', models.PositiveIntegerField(default=5, help_text='Extra time beyond end_time during which a submission is still accepted but marked as DELAYED. Accounts for mobile upload latency. Default: 5 min.', verbose_name='Grace Period (Minutes)')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished exams are hidden from students.', verbose_name='Is Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exams', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Server-recorded UTC time of submission.', null=True, verbose_name='Submitted At (UTC)')),
                ('answers_data', models.JSONField(default=dict, help_text='Dict of question_id -> selected_answer. e.g., {"q1": "A", "q2": "D"}', verbose_name='MCQ Answers')),
                ('image_urls', models.JSONField(default=list, help_text='List of uploaded CQ answer sheet image file paths.', verbose_name='CQ Image Uploads')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('DELAYED', 'Delayed'), ('MISSED', 'Missed')], db_index=True, default='SUBMITTED', max_length=10, verbose_name='Submission Status')),
                ('obtained_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Obtained Marks')),
                ('tutor_feedback', models.TextField(blank=True, help_text='Written feedback from the tutor after grading.', verbose_name='Tutor Feedback')),
                ('is_graded', models.BooleanField(db_index=True, default=False, verbose_name='Is Graded')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Graded At (UTC)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.exam', verbose_name='Exam')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Exam Submission',
                'verbose_name_plural': 'Exam Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['tutor', 'start_time'], name='exams_exam_tutor_i_c6070d_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['student', 'start_time'], name='exams_exam_student_801fac_idx'),
        ),
        migrations.AddConstraint(
            model_name='examsubmission',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_student_submission_per_exam'),
        ),
    ]
