# Generated by Django 5.2.17 on 2026-10-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_batch_exam_exam_type_exam_is_results_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.CharField(choices=[('EXAM', 'Exam'), ('ASSIGNMENT', 'Assignment')], db_index=True, default='EXAM', help_text='Differentiates between timed Exams and Assignments with deadlines.', max_length=20, verbose_name='Assessment Category'),
        ),
    ]
