# Generated by Django 5.2.17 on 2026-10-06 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_category'),
        ('students', '0003_tuition_tuitionenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='tuition',
            field=models.ForeignKey(blank=True, help_text='The Tuition this exam is assigned to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.tuition', verbose_name='Tuition'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='feedback',
            field=models.TextField(blank=True, default='', help_text='Feedback provided to the student.', verbose_name='Feedback'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='uploaded_images',
            field=models.JSONField(blank=True, default=list, help_text='List of uploaded CQ / written answer sheet photo URLs.', verbose_name='Uploaded Answer Images'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('CQ', 'Creative / Written'), ('MIXED', 'Mixed'), ('HYBRID', 'Hybrid (MCQ + CQ)')], default='HYBRID', max_length=10, verbose_name='Exam Type'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of uploaded CQ answer sheet image file paths.', verbose_name='CQ Image Uploads (Legacy)'),
        ),
    ]
