# Generated by Django 5.2.17 on 2026-10-06 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_tuition_examsubmission_feedback_and_more'),
        ('students', '0004_tuition_description_tuition_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('tuition__isnull', False), ('student__isnull', False), ('batch__isnull', False), _connector='OR'), name='exam_requires_target'),
        ),
    ]
