# Generated by Django 5.2.17 on 2026-10-06 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_exam_requires_target'),
        ('students', '0005_tuitionenrollment_left_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exam',
            name='exam_requires_target',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='batch',
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('tuition__isnull', False), ('student__isnull', False), _connector='OR'), name='exam_requires_target'),
        ),
    ]
