# Generated by Django 5.2.17 on 2026-10-06 17:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_remove_exam_exam_requires_target_remove_exam_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='late_submission_until',
            field=models.DateTimeField(blank=True, help_text='If set, submissions after the deadline are accepted until this time and flagged late.', null=True, verbose_name='Accept Late Work Until (UTC)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='negative_marks_per_wrong',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marks deducted for each wrong MCQ answer. Unanswered questions cost nothing.', max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Negative Marks per Wrong MCQ'),
        ),
        migrations.AddField(
            model_name='exam',
            name='shuffle_questions',
            field=models.BooleanField(default=False, help_text='Each student gets the MCQs in a different (stable) order.', verbose_name='Shuffle MCQ Order'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the student opened the exam.', null=True, verbose_name='Started At (UTC)'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='text_answer',
            field=models.TextField(blank=True, default='', help_text='Written answer typed by the student (alternative to photo uploads).', verbose_name='Typed Answer'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit per student for timed exams. The clock starts when the student opens the exam and never runs past end_time. Ignored for assignments.', null=True, verbose_name='Duration (Minutes)'),
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Attempt',
                'verbose_name_plural': 'Exam Attempts',
                'constraints': [models.UniqueConstraint(fields=('exam', 'student'), name='unique_attempt_per_exam_student')],
            },
        ),
    ]
