# Generated by Django 5.2.17 on 2026-10-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_timing_late_shuffle_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='written_scheme',
            field=models.JSONField(blank=True, default=list, help_text='List of written questions with their maximum marks.', verbose_name='Written Marking Scheme'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='cq_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Marks per written_scheme item id, e.g. {"<id>": 4.5}. cq_score is their sum.', verbose_name='Written Marks per Question'),
        ),
    ]
