# Generated by Django 5.2.17 on 2026-10-06 05:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade_level', models.CharField(blank=True, help_text='e.g., Grade 10, A-Level, University Year 2', max_length=50, verbose_name='Grade / Class Level')),
                ('institution', models.CharField(blank=True, max_length=150, verbose_name='School / College')),
                ('parent_name', models.CharField(blank=True, max_length=100, verbose_name="Parent's Name")),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name="Parent's Phone")),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee per complete cycle (not monthly). Snapshotted into each Cycle on creation.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Tuition Fee')),
                ('cycle_length', models.PositiveIntegerField(default=12, help_text='Number of classes per payment cycle (min 1). e.g., 8, 12, 16.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cycle Length (Classes)')),
                ('notes', models.TextField(blank=True, verbose_name='Tutor Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
