# Generated by Django 5.2.17 on 2026-10-06 06:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tuition / Batch Name')),
                ('subject', models.CharField(blank=True, max_length=150, verbose_name='Subject')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('weekly_routine', models.JSONField(default=list, help_text='JSON array of schedule slots: [{"day": "Sunday", "time": "18:00"}]', verbose_name='Weekly Routine')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Fee per Student')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='enrolled_batches', to=settings.AUTH_USER_MODEL, verbose_name='Enrolled Students')),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='tuition_batches', to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Tuition Batch',
                'verbose_name_plural': 'Tuition Batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
