# Generated by Django 5.2.17 on 2026-10-06 07:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_tuitionbatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Tuition Title')),
                ('cycle_length', models.PositiveIntegerField(default=12, help_text='Dynamic class count per cycle (e.g., 8, 12, 16).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cycle Length (Classes)')),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tuition Fee per Student per Cycle')),
                ('routine', models.JSONField(default=list, help_text='List of {"day": str, "start_time": str, "end_time": str}', verbose_name='Weekly Routine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='tuitions', to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Tuition',
                'verbose_name_plural': 'Tuitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TuitionEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_tuitions', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('tuition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.tuition', verbose_name='Tuition')),
            ],
            options={
                'verbose_name': 'Tuition Enrollment',
                'verbose_name_plural': 'Tuition Enrollments',
                'ordering': ['-joined_at'],
                'unique_together': {('tuition', 'student')},
            },
        ),
    ]
