# Generated by Django 5.2.17 on 2026-10-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_tuition_tuitionenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='subject',
            field=models.CharField(blank=True, max_length=150, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='tuitionenrollment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active Enrollment'),
        ),
    ]
