# Generated by Django 5.2.17 on 2026-10-06 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_tuition_description_tuition_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionenrollment',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Left At'),
        ),
        migrations.AlterField(
            model_name='tuitionenrollment',
            name='tuition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.tuition', verbose_name='Tuition'),
        ),
    ]
