# Generated by Django 5.2.17 on 2026-10-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_remove_exam_exam_requires_target_remove_exam_batch_and_more'),
        ('students', '0005_tuitionenrollment_left_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TuitionBatch',
        ),
    ]
