# Generated by Django 5.2.17 on 2026-10-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_delete_tuitionbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='initial_password',
            field=models.CharField(blank=True, default='', help_text='Temporary password generated or set by tutor during enrollment for distribution to the student.', max_length=128, verbose_name='Initial / Temporary Password'),
        ),
    ]
