# Generated by Django 5.2.17 on 2026-10-06 17:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def convert_to_group_model(apps, schema_editor):
    """
    1. `total_fee` used to be a per-student fee. Scale it by the number of
       active students so each tuition keeps earning the same amount as before.
    2. Turn the old `selected_tutor` pointer into ConnectionRequest rows.
    """
    Tuition = apps.get_model('students', 'Tuition')
    TuitionEnrollment = apps.get_model('students', 'TuitionEnrollment')
    ConnectionRequest = apps.get_model('students', 'ConnectionRequest')
    User = apps.get_model('authentication', 'CustomUser')

    for tuition in Tuition.objects.all():
        active = TuitionEnrollment.objects.filter(tuition=tuition, is_active=True).count()
        if active > 1:
            tuition.total_fee = tuition.total_fee * active
            tuition.save(update_fields=['total_fee'])

    for student in User.objects.filter(role='STUDENT', selected_tutor__isnull=False):
        tutor_id = student.selected_tutor_id
        enrolled = TuitionEnrollment.objects.filter(student=student, tuition__tutor_id=tutor_id).exists()
        ConnectionRequest.objects.get_or_create(
            student=student,
            tutor_id=tutor_id,
            defaults={'status': 'ACCEPTED' if enrolled else 'PENDING'},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_rename_tuition_fee_tuition_total_fee'),
        ('authentication', '0002_customuser_selected_tutor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='What the tutor earns for one complete cycle of this tuition.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Fee per Cycle (whole group)'),
        ),
        migrations.AlterField(
            model_name='tuitionenrollment',
            name='tuition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.tuition', verbose_name='Tuition'),
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10, verbose_name='Status')),
                ('message', models.CharField(blank=True, default='', max_length=500, verbose_name='Message to Tutor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded At')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connection_requests', to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Connection Request',
                'verbose_name_plural': 'Connection Requests',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'tutor'), name='unique_connection_request_per_student_tutor')],
            },
        ),
        migrations.RunPython(convert_to_group_model, migrations.RunPython.noop),
    ]
