# Generated by Django 5.2.16 on 2026-10-07 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_remove_studentprofile_initial_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description / Instructions')),
                ('due_date', models.DateTimeField(db_index=True, verbose_name='Due Date & Time')),
                ('submitted_online_url', models.URLField(blank=True, default='', help_text='Student may paste a link (Google Doc, GitHub, etc.) as their submission.', max_length=1000, verbose_name='Submitted Online URL')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('is_evaluated', models.BooleanField(default=False, help_text='Set True by the tutor after physical or online review.', verbose_name='Evaluated / Marked Done')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='Evaluated At')),
                ('tutor_feedback', models.TextField(blank=True, verbose_name='Tutor Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, help_text='Null when assigned to an entire tuition group.', limit_choices_to={'role': 'STUDENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_homework', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('tuition', models.ForeignKey(blank=True, help_text='Null when assigned to an individual student.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_assignments', to='students.tuition', verbose_name='Tuition Group')),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_homework', to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homework Assignments',
                'ordering': ['due_date'],
            },
        ),
    ]
