# Generated by Django 5.2.17 on 2026-10-07 18:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_tutor_code_profile_pic_homework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='submission_file',
            field=models.FileField(blank=True, help_text='Optional file upload as an alternative to a URL.', null=True, upload_to='homework/%Y/%m/', verbose_name='Submission File'),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'role': 'STUDENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_class_schedules', to=settings.AUTH_USER_MODEL)),
                ('tuition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='students.tuition')),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_class_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyRoutine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], db_index=True, max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'role': 'STUDENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_weekly_routines', to=settings.AUTH_USER_MODEL)),
                ('tuition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailed_routines', to='students.tuition')),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_weekly_routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('student__isnull', False), ('tuition__isnull', False), _connector='OR'), name='routine_requires_student_or_tuition'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='routine_end_after_start')],
            },
        ),
    ]
