# Generated by Django 5.2.17 on 2026-10-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_homework_submission_file_classschedule_weeklyroutine'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='source_label',
            field=models.CharField(blank=True, default='', help_text='Where this homework came from (e.g. which class). Display only.', max_length=255, verbose_name='Source Label'),
        ),
    ]
